// ========================================= HOTEL ==================================== //
### add hotel
POST http://localhost:8000/api/hotels/
Content-Type: application/json

{
    "name": "Hotel Sofitel",
    "type": "Hotel",
    "city": "Sydney",
    "address": "Australia",
    "distance": "1000",
    "title": "Best Hotel in Sydney",
    "description": "Hotel description",
    "cheapestPrice": 250
}

### update hotel
PUT http://localhost:8000/api/hotels/627e13551350d8b5e157ae49
Content-Type: application/json

{
    "name": "Hotel Del Luna" 
}

### delete hotel
DELETE http://localhost:8000/api/hotels/627e13551350d8b5e157ae49

### get hotel
GET http://localhost:8000/api/hotels/627e13551350d8b5e157ae49

### get all hotels
GET http://localhost:8000/api/hotels/


// ========================================= ROOM ==================================== //

### add room
POST http://localhost:8000/api/rooms/627e13551350d8b5e157ae49
Content-Type: application/json

{
    "title": "Luxury Room",
    "price": 250,
    "maxPeople": 2,
    "description": "King size bed, 1 Bathroom, balcony",
    "roomNumbers": [{"number": 101}, {"number": 102}]
}

### update room
PUT http://localhost:8000/api/rooms/628c52e2ad64fa4f4ba3a212
Content-Type: application/json

{
    "title": "Premium Room" 
}

### delete room
DELETE http://localhost:8000/api/rooms/628c52e2ad64fa4f4ba3a212/627e13551350d8b5e157ae49

### get room
GET http://localhost:8000/api/rooms/628c52e2ad64fa4f4ba3a212

### get all rooms
GET http://localhost:8000/api/rooms/




// ========================================= AUTH ==================================== //
### register user 
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "username": "pariwesh7",
    "email": "admin@gmail.com",
    "password": "C.ronaldo7",
    "isAdmin": true
}


### login user 
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username": "pariwesh7",
    "password": "C.ronaldo7"
}


// ========================================= USER ==================================== //
### update user
PUT http://localhost:8000/api/users/627f04187c342fb4e8b8b024
Content-Type: application/json

{
    "username": "pariwesh7"
}

### check authentication
GET http://localhost:8000/api/users/checkauthentication


